In [1]:
import numpy as np

In [2]:
arr = np.array([1,0,0,0])

In [3]:
arr[0]

1

In [4]:
np.sin(0)


0.0

In [5]:
from math import sin
import math

In [6]:
a = sin(0)
a

0.0

In [7]:
math.cos(1)

0.5403023058681398

In [11]:
np.zeros([4,1])

array([[0.],
       [0.],
       [0.],
       [0.]])

In [12]:
def test():
    return 1,2,3

In [13]:
a = test()

In [14]:
a


(1, 2, 3)

In [15]:
a[0]

1

In [21]:
x = np.ones([4,4])

In [22]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
y = np.array([[1,2,3,4]])

In [29]:
y

array([[1, 2, 3, 4]])

In [31]:
x.dot(y.T)

array([[10.],
       [10.],
       [10.],
       [10.]])

In [32]:
y = np.array(y)

In [33]:
y

array([[1, 2, 3, 4]])

In [36]:
q = np.array([1, 0, 0, 0], dtype=np.float64)
w = np.array([1,2,3])
A = np.array([[0, -w[0], -w[1], -w[2]],
                  [w[0], 0, w[2], -w[1]],
                  [w[1], -w[2], 0, w[0]],
                  [w[2], w[1], -w[0], 0]], dtype=np.float64)
dq = 0.5 * A @ q

In [38]:
dq.dtype

dtype('float64')